### ISSUE TITLE
Inherit ndexmenu JS styling from Bootstrap3

### ISSUE THREAD

**Issue by bgx4k3p** [samuelet/indexmenu#160]
Is there a way inherit the Bootstrap3 plugin theme for the sidebar? If not, is there a sample CSS somewhere? I love the functionality and use the JS sidebar, but the look is not consistent with the site theme. Thanks!

**Comment by samuelet** [comment]
bootstrap is not planned, but you can create yuor own indexmenu theme overriding its css style and images:
https://www.dokuwiki.org/plugin:indexmenu#javascript_themes

**Comment by Klap-in** [comment]
In the 'images' folder in the folder of the indexmenu plugin you can find a couple of themes, some have also a 'style.css'.

**Comment by Klap-in** [comment]
If you have built such a bootstrap theme it would be a nice addition to this theme collection, would you consider sharing it? Thanks for thinking about this!

**Comment by bgx4k3p** [comment]
I haven't built the theme, it's available as a template from DokuWiki directly: https://www.dokuwiki.org/template:bootstrap3

**Comment by Klap-in** [comment]
In the latest version an new JavaScript tree based on Fancytree is implemented.
**If** you use the bootstrap3 template, you can enable it with the options: `js#bootstrap treenew`, eventually you can add this to the default options in the Configuration Manager.

Please note: The option `js#bootstrap treenew` is not working without the bootstrap3 files. However, these are not included in the Indexmenu plugin. You need to add these files by:
 * Using the template:bootstrap3, then everything is well integrated.
 * Or include the files your self, but be _warned_ that at unexpected places small (potentially wrong) layout changes are triggered because the bootstrap3 has quite broad definitions. Including the files yourself is possible with:
   * download the bootstrap3 files yourself and include them with addStylesForUsedThemes in the action.php, 
   * or place the bootstrap3 files in the assets folder of the [Icons plugin](https://www.dokuwiki.org/plugin:icons)

(disclaimer: maybe in the future I will include all the needed files in Indexmenu, but I do not know yet if or when)
