### ISSUE TITLE
CDATA shown on page when used in sidebar

### ISSUE THREAD

**Issue by Harvie** [samuelet/indexmenu#173]
It displayed CDATA mess when i used indexmenu in sidebar. Had to change syntax/indexmenu.php from
`$out = "<script type='text/javascript' charset='utf-8'>\n";`
to
`$out = "<script type='text/javascript' charset='utf-8' style='overflow: hidden; height: 0px;' >\n";`

because something was automatically adding `style='display:block;'` one second after indexmenu was displayed. which (at least in chrome) resulted in showing CDATA as text on page. I am not sure what does this, but this workaround helps to fix that.

**Comment by magnebra** [comment]
The offending code seems to be in lib/scripts/page.js#makeToggle. The line $child = $content.children() (#132) will also return script tags if any.
The result is that they later will be have the display=block style set on them.

**Comment by Harvie** [comment]
@magnebra do you think there's some less-hacky solution than the one i've used? Anyway... it would be nice to get some kind of official fix for this...

**Comment by DevonFrosch** [comment]
We had this problem on our wiki as well. It turns out we had a missing `<div class="group">` underneath the `<div class="content">` in the main.php of the template (default: `lib/tpl/dokuwiki/main.php`).

This changed in 2015, quite a while ago (https://github.com/splitbrain/dokuwiki/commit/82246f10eb9ae3debeadf5913232105aa2694cec#diff-de0e793668ff824f0b6b6a8882ca20e3) and we missed it when we updated back then.

Hope this helps others as well, and I think it's not a bug of this plugin.

**Comment by magnebra** [comment]
I can confirm that @DevonFrosch observation is correct. Changing this in our template fixed this issue.

**Comment by Klap-in** [comment]
Great, so updating the template seems to fix this issue.
