### ISSUE TITLE
tsort nsort - mix Namespaces and Sites

### ISSUE THREAD

**Issue by LMS235** [samuelet/indexmenu#286]
After the last update the pages and namespaces are mixed, see picture:

![image](https://github.com/samuelet/indexmenu/assets/8693550/c94605da-c9dd-495d-8210-4e9c29d8911c)

with "notsort" this does not happen, but then it is sorted by page name, not by heading. 

That was different with the last version, and it should be the same again. So first the folders / namespaces, then the individual pages, don't mix them.

**Comment by LMS235** [comment]
I see the note here https://www.dokuwiki.org/plugin:indexmenu 

![image](https://github.com/samuelet/indexmenu/assets/8693550/f2c9a2f0-704e-48ce-82c8-f7201e3729a8)

But that's exactly what's supposed to happen again (I don't know why they took it out)

**Comment by Klap-in** [comment]
Before it grouped namespaces and pages. Now I sort them together, because it was a often requested feature for `nsort`.
I thought it could makes sense to join it in the nsort option.

But if this is undesired, then I could also introduce it as extra option `group`. I wondering which default makes most sense in that case. `group` or `nogroup`, I think now `nogroup` as default.

**Comment by Klap-in** [comment]
I cannot tell yet, as I work on it in my free time. Please try the previous version in the releases list of GitHub, you can use that link to install it  via the Extension Manager temporary.

**Comment by Klap-in** [comment]
I prefer grouping because often the pages with similar name are related to the namespaces with that name, which might give better overview for use as menu in sidebars.

Could explain why you prefer not grouping?

If others who see this can share there opinion as well by voting I will appropriate that:
👍 Use `nogroup` as default, thus namespaces and pages are mixed but all sorted by the type requested.
👎 Change default to `group`, thus sort namespaces and pages both, but separately grouped. (This restores behaviour to situation as before December 2023)

**Comment by LMS235** [comment]
We use this for the sidebar (as probably most people do) - which means I want to have my namespaces at the top and individual pages at the bottom (grouped as before). Because the pages have nothing to do with the namespaces (otherwise the pages would be under the corresponding namespace).

**Comment by Klap-in** [comment]
I see. I'm trying (and considering already a couple of other ideas) to make the plugin simpler and more consistent especially with sorting. Also I try to reduce the number of options.
But so far I did not yet succeed ;-) Sorry for the inconvenience here! However, it might be not the latest change unfortunately.
As you propose, it is probably better to choice the same defaults as before. I think I will indeed introduce a separate group option, and make `group` the default.

**Comment by Klap-in** [comment]
Does this work for you as expected?

**Comment by e-dschungel** [comment]
Hi,

for me its not working as expected. I'd like to sort alphabetically with no grouping (ns and pages sorted together).
{{indexmenu>.#0|nsort nogroup}} -> grouped, sort alphabetically 
{{indexmenu>.#0|rsort nogroup}} -> grouped, reversed order 
{{indexmenu>.#0|rsort nsort nogroup}} -> not grouped, but reversed order

**Comment by Klap-in** [comment]
Grouping is the default. Only if you use `nsort`, you can use `nogroup`.
However, `nsort` is only activated if you use `rsort`, `hsort`, `tsort`, `dsort` or `msort`. (I have ideas to change this, but that is longer term wish)

**Comment by e-dschungel** [comment]
Ah, thanks, a bit counter intuitive but works for me too now.

**Comment by LMS235** [comment]
@Klap-in update plugin.txt and dokuwiki plugin site?
